# Generated by Django 3.0.7 on 2020-06-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstackApp', '0002_auto_20200606_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
