# Generated by Django 3.0.7 on 2020-06-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstackApp', '0003_auto_20200606_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='varify_user',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
