# Generated by Django 3.0.7 on 2020-06-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstackApp', '0004_usersignup_varify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='varify_user',
        ),
    ]
